In [37]:
import numpy as np
a = [2,3,4,5]
b = np.array(a)
b

array([2, 3, 4, 5])

In [38]:
a = [[1,2,3] , [4,5,6] , [7 , 8 ,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a = np.random.uniform(1 , 10)
print(a)

b = np.random.uniform(1 , 10 , 15)
print(b)

3.6295725426319336
[7.57576253 8.65964256 8.25632999 8.57232753 7.43775249 3.34521635
 5.2888774  6.21280197 7.94754319 9.9545698  2.77831236 1.88600006
 4.3265511  1.49271626 9.17298251]


In [41]:
np.random.random((3 , 2))

array([[0.41298211, 0.29383788],
       [0.68706445, 0.31758071],
       [0.39661404, 0.06092782]])

In [42]:
np.random.normal(0, 1, 10)

array([ 0.20145401,  1.07362613,  0.14475771,  1.03808424, -0.8056538 ,
       -0.72485514, -1.17703739, -1.47065261,  0.23298212, -3.05180435])

In [43]:
np.random.randint(1 ,10)

8

In [44]:
np.random.randint(1 ,10 , 10)

array([3, 9, 4, 3, 8, 2, 8, 2, 6, 9])

In [45]:
a = np.random.randint(1 ,10 , 10)
np.reshape(a , (2,5))

array([[1, 6, 2, 3, 7],
       [2, 5, 6, 1, 3]])

In [46]:
np.random.rand(15)

array([0.09210551, 0.93643058, 0.68330002, 0.32562147, 0.40783841,
       0.19730786, 0.80032104, 0.77016582, 0.2715524 , 0.23007265,
       0.96111048, 0.25706749, 0.50382607, 0.02419588, 0.9102882 ])

In [47]:
np.random.rand(5,3,2)

array([[[0.23133654, 0.07359153],
        [0.1081858 , 0.06454331],
        [0.0289103 , 0.43826351]],

       [[0.82658586, 0.00120073],
        [0.26005782, 0.30912208],
        [0.30198577, 0.41871423]],

       [[0.43858463, 0.69299643],
        [0.93273445, 0.61062944],
        [0.37687447, 0.22772133]],

       [[0.46800646, 0.63639653],
        [0.70804657, 0.29954728],
        [0.29021137, 0.99940169]],

       [[0.8197994 , 0.64203177],
        [0.56250071, 0.07726798],
        [0.26548755, 0.13020497]]])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
np.linspace(0,10 , 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [58]:
x = np.arange(25).reshape(5,5)
print(x)
x.ndim
print(x.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
int32
